#baseURL = 'https://example.org/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'


baseURL = "https://caiyanch.github.io/"
languageCode =  "en-us"
defaultContentLanguage=  "zh"
title =  "ðŸ‘¨â€ðŸŒ¾ Caiyan"
# ä¸»é¢˜
theme =  "PaperMod"
publishDir =  "docs"



params:
  defaultTheme: dark
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >-
      Welcome to my website.      
  socialIcons:
    - name: email
      url: 'mailto:some@emailadres.com'
